# docker-compose.yml

version: '3'

services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: simpleuser
      POSTGRES_PASSWORD: hopla
      POSTGRES_DB: local
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    restart: always

  web:
    build: .
    command: >
      bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis

  worker:
    build: .
    command: python manage.py rqworker default
    volumes:
      - .:/app
    depends_on:
      - db
      - redis

volumes:
  postgres_data:
