# Generated by Django 5.0.4 on 2024-05-06 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="ticket",
            options={"ordering": ["-id"]},
        ),
    ]
