# Generated by Django 5.0.4 on 2024-05-06 11:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_alter_ticket_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="image",
            name="ticket",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="images",
                to="api.ticket",
            ),
        ),
    ]
